include: package:very_good_analysis/analysis_options.5.0.0.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    file_names: false
    no_default_cases: false
    avoid_redundant_argument_values: false